### PR TITLE
Remove common BC break for relative path with authority and trigger deprecations instead

### LINKED ISSUE #138: Exception handling on invalid URI modifications is a breaking change
I know that the Guzzle project doesn't state that it is following SemVer, and the [release notes](https://github.com/guzzle/psr7/releases/tag/1.4.0) clearly say:

> - Ensure each URI modification results in a valid URI according to PSR-7 discussions. Invalid modifications will throw an exception instead of returning a wrong URI or doing some magic.
>   - `(new Uri)->withPath('foo')->withHost('example.com')` will throw an exception because the path of a URI with an authority must start with a slash "/" or be empty

but I just wanted to give a notice that this change break projects that currently use invalid modifications (as it happened with some of mine, shame on me 🙂), in case that the usual "the app doesn't work anymore" bug report is brought to project maintainers. In my case, I had this code at a few places:

```php
$uri = new Uri('http://domain.tld')->withPath('path/to/location');
```

This also affects projects that require `guzzlehttp/guzzle`, which specifies `guzzlehttp/psr7: ^1.3.1` as a dependency.

:octocat:

### PR DESCRIPTION
**Pull request by Tobion**
Fixes #138 and will be released as 1.4.1

### CODE REVIEW

**Comment by jeromegamez** [comment]
When I execute the test suite (PHP 7.1.1), I get the following errors:

```
❯ phpunit
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

...............................................................  63 / 722 (  8%)
............................................................... 126 / 722 ( 17%)
............................................................... 189 / 722 ( 26%)
............................................................... 252 / 722 ( 34%)
......................F........................................ 315 / 722 ( 43%)
............................................................... 378 / 722 ( 52%)
............................................................... 441 / 722 ( 61%)
............................................................... 504 / 722 ( 69%)
............................................................... 567 / 722 ( 78%)
............................................................... 630 / 722 ( 87%)
............................................................... 693 / 722 ( 95%)
...........F.................

Time: 606 ms, Memory: 12.00MB

There were 2 failures:

1) GuzzleHttp\Tests\Psr7\StreamWrapperTest::testReturnsFalseWhenStreamDoesNotExist
Failed asserting that exception of type "\PHPUnit_Framework_Error_Warning" is thrown.

2) GuzzleHttp\Tests\Psr7\UriTest::testUriComponentsGetEncodedProperly with data set #1 ('/€?€#€', '/%E2%82%AC', '%E2%82%AC', '%E2%82%AC', '/%E2%82%AC?%E2%82%AC#%E2%82%AC')
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-/%E2%82%AC
+/%E2_%AC

/private/tmp/psr7/tests/UriTest.php:533

FAILURES!
Tests: 722, Assertions: 1727, Failures: 2.
```

File: src/Uri.php [hunk 1]
```diff
@@ -690,7 +701,13 @@ private function validateState()
                 throw new \InvalidArgumentException('A relative URI must not have a path beginning with a segment containing a colon');
             }
         } elseif (isset($this->path[0]) && $this->path[0] !== '/') {
-            throw new \InvalidArgumentException('The path of a URI with an authority must start with a slash "/" or be empty');
+            @trigger_error(
```
Comment (jeromegamez) [inline src/Uri.php]: The `@` sign mutes the warning, so that it will never be visible to the implementing developer.

File: src/Uri.php [hunk 2]
```diff
@@ -265,6 +265,12 @@ public static function isSameDocumentReference(UriInterface $uri, UriInterface $
      */
     public static function removeDotSegments($path)
     {
+        @trigger_error(
```
Comment (jeromegamez) [inline src/Uri.php]: The `@` sign mutes the warning, so that it will never be visible to the implementing developer.

File: src/Uri.php [hunk 3]
```diff
@@ -281,6 +287,11 @@ public static function removeDotSegments($path)
      */
     public static function resolve(UriInterface $base, $rel)
     {
+        @trigger_error(
```
Comment (jeromegamez) [inline src/Uri.php]: The `@` sign mutes the warning, so that it will never be visible to the implementing developer.

**Comment by Tobion** [comment]
@jeromegamez for the test failure pls see https://github.com/guzzle/psr7/pull/103#issuecomment-229820532 and report your results

File: src/Uri.php (hunk 1 above)
Comment (Tobion) [inline src/Uri.php]: Most people have an error handler that transforms any error to exception. So if you don't mute it, you could still say its a BC break for them. This approach is also used in symfony.

**Comment by jeromegamez** [comment]
That was it, thanks @Tobion!

**Comment by Tobion** [comment]
So what is it?

**Comment by jeromegamez** [comment]
```php
array(3) {
  'path' =>
  string(4) "/�_�"
  'query' =>
  string(3) "�_�"
  'fragment' =>
  string(3) "�_�"
}
```

I thought it was just an issue with my local PHP installation, that's why I didn't include the output in my first response.

**Comment by Tobion** [comment]
Feel free to report this as a php bug.

File: src/Uri.php (hunk 1 above)
Comment (jeromegamez) [inline src/Uri.php]: It is, because Symfony uses the PHPUnitBridge component to catch deprecation notices in Symfony Full Stack projects.

`E_USER_DEPRECATED` is just a notice, not an error, and will not halt program execution. It will also not be visible on properly configured production systems. (if someone has enabled `E_ALL` in their live error reporting, well… :))

Users not using the PHPUnitBridge or similar components will never see that the method is deprecated and thus not change their calls. Yes, the triggered notice might break the build pipeline, but it will not break running projects.

I am not saying that I would insist on removing the `@`, it's just that `E_USER_DEPRECATED` is meant to be used. Muting it so that e.g. PHPUnitBridge can make something out of it means making an agnostic library focusing on specific environments.

Comment (gmponos) [inline src/Uri.php]: I would like also to notice that if you do not add the mute there will be developers that their tests might fail. 

Although in some cases if they had tests they would have already made the necessary changes.

Comment (sagikazarmark) [inline src/Uri.php]: This is an accepted way if triggering deprecation errors I think. For library developers I think the `@deprecated` phpdoc is more useful when using a proper IDE. Of course if someone doesn't use something similar to the PHPUnit bridge or use IDEs these days or doesn't read CHANGELOG, then we can't really do anything about it. Also, semver is here to help: when upgrading to a new major version, tests will eventually break, so sooner or later the developer will be notified about the deprecation without breaking actual, stable code.

File: src/Uri.php [hunk 4]
```diff
@@ -265,6 +265,12 @@ public static function isSameDocumentReference(UriInterface $uri, UriInterface $
      */
     public static function removeDotSegments($path)
     {
+        @trigger_error(
+            'GuzzleHttp\Psr7\Uri::removeDotSegments is deprecated since version 1.4. ' .
```
Comment (sagikazarmark) [inline src/Uri.php]: Common pattern is to add a version where it will be removed. Maybe add it here?

File: src/Uri.php [hunk 5]
```diff
@@ -690,7 +701,13 @@ private function validateState()
...
             }
         } elseif (isset($this->path[0]) && $this->path[0] !== '/') {
-            throw new \InvalidArgumentException('The path of a URI with an authority must start with a slash "/" or be empty');
+            @trigger_error(
+                'The path of a URI with an authority must start with a slash "/" or be empty. Automagically fixing the URI ' .
+                'by adding a leading slash to the path is deprecated since version 1.4 and will throw an exception instead.',
+                E_USER_DEPRECATED
+            );
+            $this->path = '/'. $this->path;
+            //throw new \InvalidArgumentException('The path of a URI with an authority must start with a slash "/" or be empty');
```
Comment (sagikazarmark) [inline src/Uri.php]: A note would probably be nice here, just to know we need to update this.

File: tests/UriTest.php [hunk 6]
```diff
@@ -569,14 +569,12 @@ public function testAllowsForRelativeUri()
         $this->assertSame('foo', (string) $uri);
     }
 
-    /**
-     * @expectedException \InvalidArgumentException
-     * @expectedExceptionMessage The path of a URI with an authority must start with a slash "/" or be empty
-     */
-    public function testRelativePathAndAuhorityIsInvalid()
+    public function testRelativePathAndAuhorityIsAutomagicallyFixed()
```
Comment (sagikazarmark) [inline tests/UriTest.php]: Maybe leave the old test here as well (just like the commented exception). You can skip the test itself, or use `expect`method. Not sure if it's right, just an idea.

File: src/Uri.php (hunk 4 above)
Comment (Tobion) [inline src/Uri.php]: It's usually the next major version. No point in adding this.

File: src/Uri.php (hunk 5 above)
Comment (Tobion) [inline src/Uri.php]: Kinda obvious, isn't it?

File: src/Uri.php (hunk 4 above)
Comment (sagikazarmark) [inline src/Uri.php]: I mentioned because you referred to Symfony deprecation standard which includes this.

File: src/Uri.php (hunk 5 above)
Comment (sagikazarmark) [inline src/Uri.php]: Maybe it is now, but I leave it to you
