### PR TITLE
Accept null and bool header values again

### LINKED ISSUE #282: [BC Break] trimHeaderValues in 1.6 Release
With the new release, all headers are getting asserted by its type. Having said that, this introduces a BC break. Symfony's Browserkit Client for example, passes the `https` value as a boolean type:

https://github.com/symfony/symfony/blob/38b9b951a42b908fd7e7e9651e41209bc7e620d1/src/Symfony/Component/BrowserKit/AbstractBrowser.php#L385

After updating guzzlehttp/psr7 to 1.6, this request will fail.

### PR DESCRIPTION
**Pull request by Tobion**
This is not according to PSR-7 which says `@param string|string[] $value Header value(s).` but for BC and missing type declarations it makes sense.

Fixes #282

### CODE REVIEW

File: tests/ResponseTest.php [hunk 1]
```diff
@@ -263,8 +263,7 @@ public function invalidHeaderProvider()
         return [
             ['foo', [], 'Header value can not be an empty array.'],
             ['', '', 'Header name can not be empty.'],
-            ['foo', false, 'Header value must be a string or numeric but boolean provided'],
-            ['foo', new \stdClass(),  'Header value must be a string or numeric but stdClass provided.'],
+            ['foo', new \stdClass(),  'Header value must be scalar or null but stdClass provided.'],
```
Comment (GrahamCampbell) [inline tests/ResponseTest.php]: Why is there double whitespace here. ;)
