### PR TITLE
Fix request phpdoc and '0' problem

### LINKED ISSUE #86: Request has invalid documentation or invalid constructor handling
According to https://github.com/guzzle/psr7/blob/master/src/Request.php#L28-L29 the `Request` class can be created using
```php
<?php
$request = new Request(null, null);
```

However, the UriInterface validation will cause that to throw an `InvalidArgumentException`. See https://github.com/guzzle/psr7/blob/master/src/Request.php#L43-L49

Looking at the PSR-7 definition for `RequestInterface`, neither `getMethod` or `getUri` may return anything but a `string` and `UriInterface` respectively. My gut feeling is that the documentation should then be considered invalid.

### PR DESCRIPTION
**Pull request by Tobion**
Fixes #86 and the typical `'0'` problem for the Request body and getRequestTarget.

### CODE REVIEW

File: src/Request.php [hunk 1]
```diff
@@ -40,12 +38,8 @@ public function __construct(
         $body = null,
         $protocolVersion = '1.1'
     ) {
-        if (is_string($uri)) {
+        if (!($uri instanceof UriInterface)) {
             $uri = new Uri($uri);
-        } elseif (!($uri instanceof UriInterface)) {
-            throw new \InvalidArgumentException(
-                'URI must be a string or Psr\Http\Message\UriInterface'
```
Comment (Tobion) [inline src/Request.php]: we can just delegate that to the `Uri` constructor

File: src/Request.php [hunk 2]
```diff
@@ -25,13 +25,11 @@ class Request implements RequestInterface
     private $uri;
 
     /**
-     * @param null|string $method HTTP method for the request.
```
Comment (Tobion) [inline src/Request.php]: method as null will not fail because it uses `strtoupper` on it which transforms it to a string. But it should not be a documented way because it's not consistent with `getMethod` and `withMethod`
