### PR TITLE
Avoid no-url index in stream_get_meta_data

### LINKED ISSUE #411: Can't send file from stream_type MEMORY
**PHP version**: 7.3.27 (hint: `php --version`)

**Description**
```
Undefined index: uri in /app/vendor/guzzlehttp/psr7/src/Utils.php:320
```

`\stream_get_meta_data($resource)` return
```
array (
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
  'stream_type' => 'MEMORY',
  'mode' => 'rb',
  'unread_bytes' => 0,
  'seekable' => true,
)
```

**How to reproduce**

1. read 0 bytes from `bytea` field of table with `ActiveRecord` `yii2` 
(as resource from \PDOStatement::execute(); \PDOStatement::fetch(); see https://www.php.net/manual/en/class.pdostatement.php )
2. send as multipart file this resource

**Possible Solution**

```
                $metaData = \stream_get_meta_data($resource);
                if (array_key_exists('uri', $metaData) && $metaData['uri'] === 'php://input') {
```
or
```
                if (\stream_get_meta_data($resource)['uri'] ?? '' === 'php://input') {
```
**Additional context**

### PR DESCRIPTION
**Pull request by bscheshirwork**
fix #411 in 1.x branch for `"php": ">=5.4.0",`

### CODE REVIEW

File: src/Utils.php [hunk 1]
```diff
@@ -317,7 +317,8 @@ public static function streamFor($resource = '', array $options = [])
                  * The 'php://input' is a special stream with quirks and inconsistencies.
                  * We avoid using that stream by reading it into php://temp
                  */
-                if (\stream_get_meta_data($resource)['uri'] === 'php://input') {
+                $metaData = \stream_get_meta_data($resource);
+                if (array_key_exists('uri', $metaData) && $metaData['uri'] === 'php://input') {
```
Comment (GrahamCampbell) [inline src/Utils.php:321]: please use `isset`, to be the same as your other PR

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]

File: src/Utils.php (hunk 1 above)
Comment (bscheshirwork) [reply src/Utils.php]: So... I think we need to call `\stream_get_meta_data` once.

Also I think assign `$metaData` into `if`is not a cool solution.

It is look like good now?

**Review by GrahamCampbell — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]
Thank you
