### PR TITLE
accept integers as valid resource type

### LINKED ISSUE #45: Invalid resource type: integer
Hey,

Any particular reason why `stream_for` function does not accept an integer ?

It throws that exception when using a parameter like:

```php
[
    'name' => 'event',
    'contents' =>  '1'
]
```

### PR DESCRIPTION
**Pull request by marius-c**
fixes #45

### CODE REVIEW

File: src/functions.php [hunk 1]
```diff
@@ -78,6 +78,7 @@ function stream_for($resource = '', array $options = [])
 {
     switch (gettype($resource)) {
         case 'string':
+        case 'integer':
```
Comment (mtdowling) [inline src/functions.php]: Can you change this to `is_scalar` and remove the case for "string"? That would support casting any PHP scalar type to a string.

File: src/functions.php [hunk 2]
```diff
@@ -77,7 +77,7 @@ function uri_for($uri)
 function stream_for($resource = '', array $options = [])
 {
     switch (gettype($resource)) {
-        case 'string':
+        case is_scalar($resource):
```
Comment (henriquemoody) [inline src/functions.php]: Booleans are also scalar, would that be a good idea?

Comment (mtdowling) [inline src/functions.php]: That's true. If we're ok with just documenting it as "Scalar values will be cast to a string using (string), and object will be cast to a string using __toString()", then I think it should be fine... What do you think?

Comment (henriquemoody) [inline src/functions.php]: I don't think it makes sense to use `stream_for()` with a boolean value, but it's probably better than add two `case` statements (`float` and `int`) to do this validation, it's too much complexity for not so strong reasons.

Comment (marius-c) [inline src/functions.php]: From what I understand I should leave it like it is. Do you want me to add anything else ?

**Comment by mtdowling** [comment]
The code change looks good, but I'd like to see more tests be added to test the updated code.

File: src/functions.php (hunk 2 above)
Comment (marius-c) [inline src/functions.php]: @mtdowling I'm pretty busy right now. so if anyone wants to add the test is welcomed otherwise when I got some time will do the tests also.

**Comment by loga4** [comment]
When u accept this PR?

**Comment by mtdowling** [comment]
We will need tests to be added before this can be merged.

**Comment by kmorozov** [comment]
I've run into this too, so I will write some tests.
